FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

RUN apt-get update && apt-get install -y wget unzip python3 python3-pip htop
RUN pip install mlflow

EXPOSE 5000
CMD ["mlflow", "server", "--backend-store-uri", "s3://xy-mp-pipeline/", "--default-artifact-root", "s3://xy-mp-pipeline/mlflow", "--host", "0.0.0.0" --port 5000]