version: "3.8"
services:
    training:
        build:
            context: .
            dockerfile: Dockerfile.train
        environment: 
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_REGION}
            - MLFLOW_TRACKING_URI= 0.0.0.0:5000
    mlflow:
        build:
            context: .
            dockerfile: Dockerfile.mlflow