FROM python:3.9.7-slim-buster

RUN pip install update pip

RUN pip install mlflow boto3

CMD ["mlflow", "server", "--default-artifact-root", "s3://xy-mp-pipeline/", "--artifacts-destination", "s3://xy-mp-pipeline/mlflow", "--host", "0.0.0.0", "--port", "5000"]
# ENTRYPOINT [ "/bin/sh" ]